name: Laravel

on:
  push:
    branches: [ "dev", "main" ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible-dev.yml
        key: ${{secrets.SSH_PRIVATE_KEY_PROD}}
        inventory: ${{vars.ANSIBLE_INVENTORY}}
